---
  ansible_port: 22                                # SSH Port
  ansible_user: Z80003                              # USER used for deploy
  ansible_password: ZCOBOL                        # USER used for deploy
  ansible_ssh_pipelining: True                    # needed for encoding on ssh connections
  # System Related Variables
  zoau_home: /z/python/zoau-v1.0.3                 # Path for your ZOAU directory
  python_path: /z/python/usr/lpp/IBM/cyp/v3r8/pyz  # Path for your Python
  ansible_python_interpreter: "{{python_path}}/bin/python3"
  _TAG_REDIR_ERR: txt
  _TAG_REDIR_IN: txt
  _TAG_REDIR_OUT: txt
  tgt_tmp_dir: "/tmp"
  ctl_tmp_dir: "/tmp"